builders:
  etebase_client_builder:
    import: "tool/etebase_builder.dart"
    builder_factories: ["etebaseClientBuilder"]
    build_extensions: { ".dart": [".client.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - freezed|freezed
  etebase_isolate_builder:
    import: "tool/etebase_builder.dart"
    builder_factories: ["etebaseIsolateBuilder"]
    build_extensions: { ".dart": [".isolate.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - freezed|freezed

targets:
  $default:
    builders:
      etebase:etebase_client_builder:
        enabled: true
        generate_for:
          - lib/src/gen/ffi/libetebase.ffi.dart
      etebase:etebase_isolate_builder:
        enabled: true
        generate_for:
          - lib/src/gen/ffi/libetebase.ffi.dart
