name: etebase
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.3 <3.0.0"

dependencies:
  ffi: ^2.0.1
  meta: ^1.8.0

dev_dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  build_config: ^1.1.1
  build_runner: ^2.3.2
  code_builder: ^4.3.0
  dart_pre_commit: ^4.0.0
  dart_test_tools: ^4.5.3+1
  ffigen: ^7.2.0
  source_gen: ^1.2.6
  source_helper: ^1.3.3
  test: ^1.16.0

ffigen:
  output: lib/gen/ffi/libetebase.ffi.dart
  name: LibEtebaseFFI
  description: Bindings for libetebase
  headers:
    entry-points:
      - /usr/include/etebase/etebase.h
  compiler-opts:
    - "-I/usr/lib/clang/14.0.6/include/"
  macros:
    include:
      - ETEBASE_.*
  globals:
    include:
      - ETEBASE_.*
  enums:
    include:
      - Etebase_.*
  structs:
    include:
      - Etebase.*
  unions:
    include:
      - Etebase.*
  functions:
    include:
      - etebase_.*
  comments: true
  preamble: >-
    // ignore_for_file:
    require_trailing_commas,
    non_constant_identifier_names,
    prefer_expression_function_bodies,
    lines_longer_than_80_chars,
    comment_references,
    avoid_positional_boolean_parameters,
    camel_case_types
