name: etebase
description: Dart client library for etebase using FFI bindings with libetebase
version: 1.0.2
homepage: https://github.com/Skycoder42/etebase-dart

environment:
  sdk: "^3.0.0"

platforms:
  linux:
  macos:
  windows:
  android:
  ios:

dependencies:
  ffi: ^2.0.2
  freezed_annotation: ^2.4.1
  meta: ^1.9.1
  synchronized: ^3.1.0

dev_dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.6
  code_builder: ^4.5.0
  custom_lint: ^0.5.0
  dart_pre_commit: ^5.2.0+1
  dart_test_tools: ^5.2.0
  ffigen: ^9.0.1
  freezed: ^2.4.1
  mocktail: ">=0.3.0 <2.0.0"
  source_gen: ^1.4.0
  source_helper: ^1.3.4
  test: ^1.24.4
  uuid: ^3.0.7

ffigen:
  output: lib/src/gen/ffi/libetebase.ffi.dart
  name: LibEtebaseFFI
  description: Bindings for libetebase
  headers:
    entry-points:
      - /usr/include/etebase/etebase.h
  compiler-opts:
    - "-I/usr/lib/clang/14.0.6/include/"
  macros:
    include:
      - ETEBASE_.*
  globals:
    include:
      - ETEBASE_.*
  enums:
    include:
      - Etebase_.*
  structs:
    include:
      - Etebase.*
  unions:
    include:
      - Etebase.*
  functions:
    include:
      - etebase_.*
  comments: true
  preamble: >-
    // ignore_for_file:
    require_trailing_commas,
    non_constant_identifier_names,
    prefer_expression_function_bodies,
    lines_longer_than_80_chars,
    comment_references,
    avoid_positional_boolean_parameters,
    camel_case_types,
    public_member_api_docs

cider:
  link_template:
    tag: https://github.com/Skycoder42/etebase-dart/releases/tag/etebase-v%tag%
    diff: https://github.com/Skycoder42/etebase-dart/compare/etebase-v%from%...etebase-v%to%
