version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/etebase"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/etebase_flutter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
