name: etebase_flutter
description: Flutter platform plugins for the dart bindings of libetebase
version: 1.0.1
homepage: https://github.com/Skycoder42/etebase-dart

environment:
  sdk: "^3.0.0"
  flutter: ">=3.10.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  etebase: ^1.0.1+1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  custom_lint: ^0.5.0
  dart_pre_commit: ^5.2.0+1
  dart_test_tools: ^5.1.3

flutter:
  plugin:
    platforms:
      android:
        package: de.skycoder42.etebase_flutter
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterAndroid
      ios:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterIos
      linux:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterLinux
      macos:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterMacos
      windows:
        pluginClass: EtebaseFlutterPluginCApi
        dartPluginClass: EtebaseFlutterWindows

cider:
  link_template:
    tag: https://github.com/Skycoder42/etebase-dart/releases/tag/etebase_flutter%2Fv%tag%
    diff: https://github.com/Skycoder42/etebase-dart/compare/etebase_flutter%2Fv%from%...etebase_flutter%2Fv%to%
