name: etebase_flutter
description: Flutter platform plugins for the dart bindings of libetebase
version: 1.1.1
homepage: https://github.com/Skycoder42/etebase-dart

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  etebase: ^1.0.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  custom_lint: ^0.6.2
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.6.2

flutter:
  plugin:
    platforms:
      android:
        package: de.skycoder42.etebase_flutter
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterAndroid
      ios:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterIos
      linux:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterLinux
      macos:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterMacos
      windows:
        pluginClass: EtebaseFlutterPluginCApi
        dartPluginClass: EtebaseFlutterWindows

cider:
  link_template:
    tag: https://github.com/Skycoder42/etebase-dart/releases/tag/etebase_flutter-v%tag%
    diff: https://github.com/Skycoder42/etebase-dart/compare/etebase_flutter-v%from%...etebase_flutter-v%to%
