name: etebase_flutter
description: Flutter extensions for the dart bindings of libetebase
version: 1.0.0
homepage: https://github.com/Skycoder42/etebase-dart

# TODO remove
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  etebase: ^1.0.0-alpha.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  dart_pre_commit: ^4.0.0
  dart_test_tools: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: de.skycoder42.etebase_flutter
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterAndroid
      ios:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterIos
      linux:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterLinux
      macos:
        pluginClass: EtebaseFlutterPlugin
        dartPluginClass: EtebaseFlutterMacos
      windows:
        pluginClass: EtebaseFlutterPluginCApi
        dartPluginClass: EtebaseFlutterWindows
