name: CI/CD for etebase

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/etebase/**"
      - ".github/workflows/etebase.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/etebase/**"
      - ".github/workflows/etebase.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      platforms: '["linux", "windows", "macos"]'
      workingDirectory: packages/etebase
      buildRunner: true
      buildRunnerArgs: >-
        --delete-conflicting-outputs
        --define etebase:etebase_client_builder=restoreMode=true
        --define etebase:etebase_isolate_builder=restoreMode=true
      unitTestPaths: test/unit
      integrationTestPaths: test/integration
      integrationTestSetup: >-
        {
          "linux": "bash tool/integration/build_unix.sh",
          "macos": "bash tool/integration/build_unix.sh packages/etebase/tool/integration/libetebase-macos.patch",
          "windows": "powershell -File tool\\integration\\build_win.ps1"
        }
  # cd:
  #   name: CD
  #   uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
  #   needs:
  #     - ci
  #   with:
  #     workingDirectory: packages/etebase
  #     buildRunner: true
  #     buildRunnerArgs: >-
  #       --delete-conflicting-outputs
  #       --define etebase:etebase_client_builder=restoreMode=true
  #       --define etebase:etebase_isolate_builder=restoreMode=true
  #     tagPrefix: etebase/v
  #   secrets:
  #     PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
