name: CD - Publish etebase_flutter to pub.dev

on:
  push:
    tags:
      - "etebase_flutter-v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    with:
      workingDirectory: packages/etebase_flutter
      tagPrefix: etebase_flutter-v
      flutter: true
      extraArtifacts: >-
        {
          "path": "artifacts"
        }
      prePublish: bash tool/libetebase/all.sh 0.5.4 artifacts
