name: CI/CD for etebase_flutter

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/etebase_flutter/**"
      - ".github/workflows/etebase_flutter_ci.yaml"
      - ".github/workflows/etebase_flutter_cd.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: packages/etebase_flutter
      buildRunner: false
      unitTestPaths: ""
      integrationTestProject: example
      integrationTestPaths: integration_test
      integrationTestCacheConfig: >-
        {
          "key": "etebase_flutter-libetebase-v0.5.5",
          "path": ".cache"
        }
      integrationTestSetup: >-
        {
          "android": "bash tool/libetebase/android.sh 0.5.5 darwin-x86_64",
          "ios": "bash tool/libetebase/ios.sh 0.5.5",
          "linux": "bash tool/libetebase/linux.sh 0.5.5",
          "macos": "bash tool/libetebase/macos.sh 0.5.5",
          "windows": "bash tool/libetebase/windows.sh 0.5.5"
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/etebase_flutter
      tagPrefix: etebase_flutter-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
