name: CI/CD for etebase_flutter

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/etebase_flutter/**"
      - ".github/workflows/etebase_flutter.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/etebase_flutter/**"
      - ".github/workflows/etebase_flutter.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      platforms: '["android", "ios", "linux", "macos", "windows"]'
      workingDirectory: packages/etebase_flutter
      buildRunner: false
      unitTestPaths: ""
      integrationTestProject: example
      integrationTestPaths: integration_test
      integrationTestCacheConfig: >-
        {
          "key": "etebase_flutter-libetebase-v0.5.3",
          "path": ".cache"
        }
      integrationTestSetup: >-
        {
          "android": "bash tool/libetebase/android.sh 0.5.3 darwin-x86_64",
          "ios": "bash tool/libetebase/ios.sh 0.5.3",
          "linux": "bash tool/libetebase/linux.sh 0.5.3",
          "macos": "bash tool/libetebase/macos.sh 0.5.3",
          "windows": "bash tool/libetebase/windows.sh 0.5.3"
        }

  libetebase:
    name: Prepare CD artifacts
    needs:
      - ci
    if: github.ref == 'refs/heads/main'
    env:
      libetebaseVersion: 0.5.3
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android
          - ios
          - macos
          - windows

        include:
          - platform: android
            os: ubuntu-latest
          - platform: ios
            os: macos-latest
          - platform: macos
            os: macos-latest
          - platform: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - id: libetebase-cache
        name: Restore libetebase from cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ matrix.platform }}-etebase_flutter-libetebase-v${{ env.libetebaseVersion }}
          path: .cache
      - name: Checkout repository
        if: steps.libetebase-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Build library if not restored
        if: steps.libetebase-cache.outputs.cache-hit != 'true'
        run: bash tool/libetebase/${{ matrix.platform }}.sh ${{ env.libetebaseVersion }}
        working-directory: packages/etebase_flutter
      - name: Generate cache artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: libetebase-${{ matrix.platform }}-${{ env.libetebaseVersion }}
          path: .cache/
          retention-days: 1

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    needs:
      - ci
      - libetebase
    with:
      workingDirectory: packages/etebase_flutter
      buildRunner: false
      restoreArtifacts: >-
        {
          "path": "artifacts"
        }
      prePublish: bash tool/libetebase/all.sh 0.5.3 artifacts
      tagPrefix: etebase_flutter/v
    secrets:
      PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
