name: CD - Publish etebase_flutter to pub.dev

on:
  push:
    tags:
      - "etebase_flutter-v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      environment: pub-deploy
      tagPrefix: etebase_flutter-v
      workingDirectory: packages/etebase_flutter
      flutter: true
      prePublish: dart run tool/libetebase/download.dart 0.5.5
