name: CI/CD for etebase_flutter

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/etebase_flutter/**"
      - ".github/workflows/etebase_flutter_ci.yaml"
      - ".github/workflows/etebase_flutter_cd.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: packages/etebase_flutter
      buildRunner: false
      unitTestPaths: ""
      integrationTestProject: example
      integrationTestPaths: integration_test
      integrationTestSetup: >-
        {
          "android": "tool/setup/macos.sh 0.5.5 android",
          "ios": "tool/setup/macos.sh 0.5.5 ios",
          "linux": "tool/setup/linux.sh 0.5.5 linux",
          "macos": "tool/setup/macos.sh 0.5.5 macos",
          "windows": "bash tool/setup/windows.sh 0.5.5 windows",
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/etebase_flutter
      tagPrefix: etebase_flutter-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
