name: CI/CD for etebase_flutter

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/etebase_flutter/**"
      - ".github/workflows/etebase_flutter_ci.yaml"
      - ".github/workflows/etebase_flutter_cd.yaml"
      - "!packages/etebase_flutter/tool/libetebase/**"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: packages/etebase_flutter
      buildRunner: false
      unitTestPaths: ""
      integrationTestProject: example
      integrationTestPaths: integration_test
      integrationTestSetup: >-
        {
          "android": "dart run tool/libetebase/download.dart 0.5.6 android",
          "ios": "dart run tool/libetebase/download.dart 0.5.6 ios",
          "linux": "dart run tool/libetebase/download.dart 0.5.6 linux",
          "macos": "dart run tool/libetebase/download.dart 0.5.6 macos",
          "windows": "dart run tool/libetebase/download.dart 0.5.6 windows"
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/etebase_flutter
      tagPrefix: etebase_flutter-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
