name: Compile native libetebase binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/rust-ci-improvements # TODO remove
    paths:
      - packages/etebase_flutter/tool/libetebase/**
      - .github/workflows/libetebase.yaml
  schedule:
    - cron: "47 2 * * 2"

env:
  libetebaseVersion: 0.5.5

jobs:
  build:
    name: Update binaries
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android_arm64-v8a
          - android_armeabi-v7a
          - android_x86_64
          - android_x86
          - ios_arm64
          - ios_simulator_arm64
          - ios_simulator_x86_64
          - linux
          - macos_arm64
          - macos_x86_64
          - windows

        include:
          - platform: ios_arm64
            runs-on: macos-latest
          - platform: ios_simulator_arm64
            runs-on: macos-latest
          - platform: ios_simulator_x86_64
            runs-on: macos-latest
          - platform: macos_arm64
            runs-on: macos-latest
          - platform: macos_x86_64
            runs-on: macos-latest
    runs-on: ${{ matrix.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install minisign
        uses: ./.github/actions/install-minisign
      - name: Build libetebase binaries
        run: dart run tool/libetebase/build.dart '${{ matrix.platform }}' '${{ env.libetebaseVersion }}'
        working-directory: packages/etebase_flutter
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: libetebase-${{ matrix.platform }}
          path: ${{ runner.temp }}/libetebase-${{ matrix.platform }}
          if-no-files-found: error
          retention-days: 1

  update_release:
    name: Update release with new binaries
    needs:
      - build
    runs-on: macos-latest # needed for lipo
    permissions:
      contents: write
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install minisign
        uses: ./.github/actions/install-minisign
      - name: Download all binary artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create secret key for minisign
        run: echo '${{ secrets.MINISIGN_SECRET_KEY }}' > '${{ runner.temp }}/minisign.key'
      - name: Build release archives
        run: dart run tool/libetebase/publish.dart '${{ env.libetebaseVersion }}'
        working-directory: packages/etebase_flutter
      - name: Cleanup minisign key
        if: always()
        run: rm -f '${{ runner.temp }}/minisign.key'
      # - name: Create or update release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: libetebase-binaries/v${{ env.libetebaseVersion }}
      #     name: "[INTERNAL] Precompiled libetebase binaries v${{ env.libetebaseVersion }}"
      #     body: Internal release of precompiled libetebase binaries, required for the etebase_libs package.
      #     prerelease: true
      #     files: publish/*
      #     fail_on_unmatched_files: true
